### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1234]
Some installation commands in our documentation are outdated or innacture:

* [x] The download command on [this page](https://vector.dev/docs/setup/installation/manual/from-archives#2-download--unpack-the-archive) for downloading Vector archives contains code
    
    ```bash
    curl -o <release-download-url> | tar -xzf --directory="vector" --strip-components=1
    ```
    
    which doesn't work.
    
    The reason is missing dash after `-xzf` and `-o` `curl` option which expects a file.
    
    I think we could change it to
    
    ```bash
    mkdir -p vector && curl -sSfL --proto '=https' --tlsv1.2 <release-download-url> | tar xzf - -C vector --strip-components=2
    ```

* [x] The [download commands for source archives](https://vector.dev/docs/setup/installation/manual/from-source#3-download-vectors-source) can be changed similarly for `master` branch:

    ```bash
    mkdir -p vector && curl -sSfL --proto '=https' --tlsv1.2 https://github.com/timberio/vector/archive/master.tar.gz | tar xzf - -C vector --strip-components=1
    ```

* [ ] The download URL for `latest` source [on the same page](https://vector.dev/docs/setup/installation/manual/from-source#3-download-vectors-source), which is currently https://vector.dev/docs/setup/installation/manual/from-source#3-download-vectors-source, returns 404 error.
* [x] [This command for source archives](https://vector.dev/docs/setup/installation/manual/from-source#systemd) needs to be changed to
    ```bash
    cp -av distribution/systemd/vector.service /etc/systemd/system
    ```
    and [this command for binary archives](https://vector.dev/docs/setup/installation/manual/from-archives#systemd) to
    ```bash
    cp -av etc/systemd/vector.service /etc/systemd/system
    ```cp -av etc/systemd/vector /etc/systemd/systemcp -av etc/systemd/vector /etc/systemd/system
* [x] There is no Windows installation page. We need to provide links to our`zip` archives (which should look like https://packages.timber.io/vector/0.6.0/vector-x86_64-pc-windows-msvc.zip). These archives contain directory named `vector-x86_64-pc-windows-msvc` with the same structure as releases for other platforms.

**Comment by a-rodin** [comment]
There is also another issue, the button "Edit this page" on docs pages doesn't work.

**Comment by a-rodin** [comment]
The link https://vector.dev/#performance on https://vector.dev page doesn't work.

**Comment by binarylogic** [comment]
Thanks! Let me know if you find anything else.

**Comment by a-rodin** [comment]
@binarylogic I've noticed that the font for "define one or more data sources" is a serif font, while I didn't see serif fonts anywhere else in the docs. Is this intended?

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/1885277/69535452-095b3880-0f8d-11ea-9919-56698e51c4bd.png">

**Comment by binarylogic** [comment]
No, that should be using the system font. I'll update. Thanks for pointing it out.
