### ISSUE TITLE
Implement custom DNS in all the sinks

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1307]
We should go through all the sinks and ensure they use the new `dns::Resolver`. The sinks that should be updated are listed below.

- [x] `aws_s3`
- [x] `aws_cloudwatch_metrics`
- [x] `aws_cloudwatch_logs`
- [x] `aws_kinesis_streams`
- [x] `clickhouse`
- [x] `datadog_metrics`
- [x] `elasticsearch`
- [x] `http`
- [x] `kafka`
- [x] `prometheus`
- [x] `splunk_hec`
- [x] `statsd`
- [x] `tcp`
- [x] `vector`
- [x] All health checks also use the resolver

This should be done through a combination of implementing the correct trait for the hyper client's resolve feature and manually calling `lookup_ip` instead of `to_socket_addrs`.

**Comment by LucioFranco** [comment]
Currently, this is blocked by #1144 and #1306.
