### ISSUE TITLE
Specification for on-disk buffering changes

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1418]
Blocked by #1417 

Once we have a game plan that is proven by #1417, I'd like a specification outlining the changes we'd like to introduce. This should get buy-in from the rest of the team and ensure we're making the optimal changes to avoid having to optimize disk buffers again 😄 .

- [ ] Add specification as a comment to this issue
- [ ] Get buy-in from the rest of the team
- [ ] Create issues representing the work

**Comment by LucioFranco** [comment]
As mentioned in #1417, I don't think it currently makes sense to update our on disk buffer. Therefore, I am going to close this issue.

Related comment https://github.com/timberio/vector/issues/1417#issuecomment-571786715
