### ISSUE TITLE
New `logfmt_parser` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1482]
A simple transform that parses [logfmt](https://brandur.org/logfmt).

There's a lot to be said about this format 😄, such as nested key support, implicit typing, and so on. To start we should:

- [ ] Produce flat structures only. Ex: keys with `.` characters will not result in nested structures. We can consider adding this as an option later.
- [ ] Make a best effort to coerce numbers.
- [ ] Support the `types` sub-table that is available in other parsers (`regex_parser`).

**Comment by lukesteensen** [comment]
> Make a best effort to coerce numbers.

Does this means something outside of the normal `types` subtable? The current implementation in #1541 does not attempt to detect any types automatically.

**Comment by binarylogic** [comment]
That's true. Why don't we open a separate issue for discussion then?
