### ISSUE TITLE
The road to 1.0

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1538]
Vector is fast approaching 1.0 and we want to be as transparent as possible with our development and planning efforts.

## 1.0 Roadmap

- [X] Initial logs support ([milestone #2](https://github.com/timberio/vector/milestone/2))
- [X] Securely process data ([milestone #11](https://github.com/timberio/vector/milestone/11))
- [X] Best-in-class `file` source ([milestone #16](https://github.com/timberio/vector/milestone/16))
- [X] Initial metrics support ([milestone #15](https://github.com/timberio/vector/milestone/15))
- [X] Initial containers support ([milestone #14](https://github.com/timberio/vector/milestone/14))
- [X] Initial AWS support ([milestone #2](https://github.com/timberio/vector/milestone/2))
- [ ] Initial GCP support ([milestone #17](https://github.com/timberio/vector/milestone/17))
- [X] Support popular targets and CPU archs ([milestone #18](https://github.com/timberio/vector/milestone/18))
- [X] Config testing ([milestone #19](https://github.com/timberio/vector/milestone/19))
- [ ] Server level metrics collection ([milestone #22](https://github.com/timberio/vector/milestone/22))
- [ ] Config consistency & cleanup ([milestone #25](https://github.com/timberio/vector/milestone/25))
- [ ] Data processing & scripting ([milestone #23](https://github.com/timberio/vector/milestone/23))
- [ ] Vector observability ([milestone #24](https://github.com/timberio/vector/milestone/24))
- [ ] Formalize regression control ([milestone #12](https://github.com/timberio/vector/milestone/12))
- [ ] Enrich data with environment context ([milestone #20](https://github.com/timberio/vector/milestone/20))

## What does 1.0 mean to us?

* **A stable API.** [As defined by semantic versioning](https://semver.org/#spec-item-5). This includes any user-facing part of Vector: the CLI, configuration schema, and everything exposed through Vector's [components](https://vector.dev/components/).
* **Production readiness.** High confidence that Vector will perform well in large demanding production environments. You can read more about he we define "production readiness" [here](https://vector.dev/docs/about/guarantees/#prod-ready).
* **Achieves Vector's vision.** A single tool that collects _all_ observability data and gets it to its destination.

## What does pre-1.0 mean to us?

* Possible API changes. Although, we do not take this lightly and will try to bundle breaking changes into a single release to reduce the migration burden.
*  Possible roadmap changes. We work closely with many Vector users and learn a lot in that process. These findings are likely to alter the 1.0 roadmap in non-substantial ways.

## What about post 1.0?

We will be focusing heavily on end-to-end use cases and going deeper on quality within the context of these use cases. For example:

* A constant focus on performance, reliability, and usability
* Application observability
* Infrastructure monitoring
* Security & compliance
* Improved parsing & structuring
* Extending Vector with plugins

**Comment by jadbaz** [comment]
Hello,
The last milestone on the roadmap is in May 2022
So this seems to be outdated
Any other updated documentation on 1.0 roadmap?

**Comment by pront** [comment]
Hello, for anyone interested we still want to hit v1 but that won't happen until at least H2 2025.

**Comment by shalk** [comment]
Is there any update for this ?

**Comment by pront** [comment]
> Is there any update for this ?

We had a few internal discussions but this is not a top priority for the short term. Did you have any additional feedback or concerns?

**Comment by shalk** [comment]
> > Is there any update for this ?
> 
> We had a few internal discussions but this is not a top priority for the short term. Did you have any additional feedback or concerns?

Thank you for your quickly reply. 

I am interested in "Fleet wide management" mentioned on the road map.

When vectors is deployed on a lots of  virtual machines, fleet management is a good feature to do some configuration management.

For Grafana Alloy have support fleet  api, So I want to know is any proposal about fleet management ?

**Comment by pront** [comment]
> I am interested in "Fleet wide management" mentioned on the road map.

This issue contains significantly outdated information. If you want to open a discussion around idea place [create a new one](https://github.com/vectordotdev/vector/discussions/new?category=general).

Or for concrete feature request please [create one here](https://github.com/vectordotdev/vector/issues/new?template=feature.yml).
