### ISSUE TITLE
Dynamic coercion/typing

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1542]
Currently, the `coerce` transform, and parsing transforms, [offer a `types` table](https://vector.dev/docs/reference/transforms/regex_parser/#types) that allows users to explicitly coercer field values. This is ideal for pipelines that must guarantee consistent field typing, but there are use cases where dynamic typing might be preferred. For these, I propose that we add a `types.auto` option. Specifically:

- [ ] Add a boolean `auto` option the `types` table for [all parser transforms](https://vector.dev/components/).
- [ ] Explicit types, as they exist currently, always take priority and should override automatic typing.
- [ ] Integer strings should automatically be coerced to integers.
- [ ] Float strings should automatically be coerced to floats.
- [ ] Boolean strings as defined by [this comment](https://github.com/timberio/vector/blob/fff92728c9490824ff9d0ae76669adc901bb5499/src/types.rs#L164-L168) should automatically coerce to boolean.
- [ ] ISO8601 time formats should automatically coerce to timestamps. I'm open to other popular formats within reason.

I'm curious what others think about this before we proceed with the work.

**Comment by bruceg** [comment]
Most of these seem relatively uncontroversial, as the conversion is effectively lossless—converting into the type and back produces the same string (or at least very close to the same)—except for two. Automatically converting into boolean could end up rewriting some strings (ie `yes` becomes `true` when reinterpreted as a string). Timestamps would potentially also have issues, depending on their output formatting (ie JSON has no such type, so we have to convert back to string). As this could lead to surprising results, it would need to be very carefully documented.

**Comment by binarylogic** [comment]
Closing in favor of #5728
