### ISSUE TITLE
Ability to drop unspecified fields in the coercer transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1632]
It'd be nice to add a simple `drop_unspecified` fields option in the `coercer` transform.

- [ ] Setting this to `true` would drop any field not specified in the `types` table.
- [ ] Setting this to `false` (default) would pass through any fields not specified.
- [ ] We should add a note in the docs about not dropping `timestamp` and `message`. While this is up to the user, these fields are important and removing them could create a frustrating UX.
