### ISSUE TITLE
New `dedupe` transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1732]
This came out of meetings with a few users. Many of them have built custom configured transforms that de-duplicate messages. There are a few definitions on this:

1. Literally duplicate events (all attributes).
2. All attributes except the `timestamp` field.
3. Only the `timestamp`, `message`, and `host` attributes (most common).
4. A configurable list of attributes.

All of this would be detected within a configurable time window. This is especially important for very high volume setups.

## Example

```toml
[transforms.deduper]
  type = "dedupe"
  fields.blacklist = ["timestamp"] # default
  fields.whitelist = [] # default
  window_seconds = 300 # default, 5 minutes
```

## Requirements

- [ ] We should start with a probabilistic algorithm that is much more memory efficient by sacrificing a _configurable_ amount accuracy.
- [ ] Field order should not matter. For example `{"key1": "value1", "key2": "value2"}` should be equal to `{"key2": "value2", "key1": "value1"}`.
- [ ] Memory usage should be carefully thought through and tested for common use cases. We should be able to provide an algorithm or guidance on expected memory usage.

**Comment by lukesteensen** [comment]
I'd be curious about the windowing expectations here. There are ways to get clever, but this will be fundamentally limited by the size of the set of previous messages to check against. Especially for use in high-volume setups, things like memory use and performance will be serious concerns.

**Comment by binarylogic** [comment]
Blocked by #1598

**Comment by lukesteensen** [comment]
This is actually not blocked by #1598 because we can make the yes/no call as events come in. That issue only blocks cases where we need to schedule outputting events independently of events coming in as input.

**Comment by binarylogic** [comment]
Ah, got it. I'll update.

**Comment by stbrody** [comment]
One of the major design considerations is around how we manage our buffer of recent Events to match against.  If we buffer a (tunable) fixed number of events, the implementation becomes significantly simpler and can likely delegate a lot of the work to rust's [lru cache](https://docs.rs/lru/0.4.3/lru/struct.LruCache.html) implementation.  If we want to buffer based on a time window, then the design gets a bit more complicated as the internal buffer must be of a variable size.

**Comment by stbrody** [comment]
# Design proposal using fixed-size buffer

## Config specification
```toml
[transforms.deduper]
  type = "dedupe"
  fields.match = ["timestamp"] # default
  buffer.num_entries = 5000 # default
```

## Implementation details
Buffering a fixed number of entries allows us to keep a fairly simple design and delegate most of the work to rust’s [lru cache](https://docs.rs/lru/0.4.3/lru/struct.LruCache.html) implementation.  At startup we will instantiate an LruCache object of the size specified by “buffer.num_entries”.  Then, as new events come into the transform, we will build a tuple of the values of all fields specified in “fields.match” and check if it is already present in the cache.  If not we output the Event from the Transform, if so we ignore the Event.  In either case we insert the tuple built from the new Event into the LruCache.  The tuple will be used as the key, the ‘value’ of the entries in the cache don’t matter since all we care about is whether key is included the cache or not, thus all values in the cache will be hard coded to the boolean value “true”.

## Behavior
This approach has the advantage of having low (constant) performance and memory cost.  The memory requirements are fixed and easy to reason about (directly linear to the configured “buffer.num_entries”).  False positives are impossible, meaning we will never drop a unique event because we incorrectly conclude it is a duplicate.  False negatives are possible, meaning we may still output duplicate events.  The rate of false negatives can be decreased by increasing the size of the buffer.

**Comment by stbrody** [comment]
# Design proposal using variable-size buffer based on a time window

## Config specification
```toml
[transforms.deduper]
  type = "dedupe"
  fields.match = ["timestamp"] # default
  buffer.seconds = 300 # default, 5 minutes
```

## Implementation details
The main structure backing the buffer will be a vector of structs corresponding to incoming Events.  The first field in each entry struct will be the timestamp of the Event, and the second will be a tuple containing the values of all fields specified in “fields.match”.  Additionally, there will be a hash map whose keys are the same tuple of values from “fields.match” and whose values are pointers into the corresponding entry in the vector.  When a new event is received, a tuple is built based on the fields specified in “fields.match” and that tuple is inserted into the vector.  That tuple is then looked up in the hash map.  If no entry is found in the map, then the tuple is inserted into the hash map, pointing to the just added entry in the vector, and the Event is outputted from the Transform.  If an entry *is* found in the hash map, then its value is updated to point to the newly added entry in the vector, and the Event is ignored by the Transform.  To handle aging out old entries, every time an Event is received we also check entry at the head of the vector to see if its timestamp has expired past the configured window.  If so, items are removed from the head of the vector until the timestamp of the head element is once again within the configured window. 

## Behavior
This approach maintains a low (amortized constant time) performance cost but adds a linear memory cost relative to the number of events that come in within the configured time window.  This memory consumption has no ceiling and for very high-volume workloads could wind up consuming significant memory.

There is no possibility of a false negative or positive within the configured time window, false negatives (meaning outputting duplicate events) remain possible when the duplicate event was received long enough ago that it has aged out of the configured time window.

This approach also introduces a new dependency on monotonically increasing timestamps.  If the timestamps ever went backwards, Events whose timestamps have aged out of the configured window may remain in the buffer until the Events before them in the buffer with higher timestamps also expire.  This could lead to unbounded memory growth if for instance the clock jumped forward by a large amount then was restored back to the proper time.  We could mitigate this concern by logging a warning anytime the timestamp of incoming events went backwards.

## Alternate implementation
If we want to avoid the additional dependency on monotonically increasing clock time, we could use a priority queue with timestamp as the priority instead of a vector as the underlying buffer.  The downside of this approach is that it adds an O(log n) performance cost on each new Event received (where n is the number of Events received in within the configured time window).  I assumed that performance cost was unacceptable which is why I proposed the vector-based solution above instead.

**Comment by stbrody** [comment]
## Likely extension: Match all fields except those specified
As a follow-up, we could add a "fields.ignore" config option.  Only one of "fields.match" and "fields.ignore" will be allowed to be specified at a time.  Everything else would work the same, but when building the tuples to store in the buffer vector or lookup table we would build them based on all fields found in the Event except those specified in “fields.ignore”.

**Comment by binarylogic** [comment]
Thanks @stbrody, I'm going to have @Hoverbear review your approach before we begin work.

**Comment by Hoverbear** [comment]
A`buffer.num_entries` seems like a much safer approach memory wise. The time-limiting approach seems a bit complex (a vector and a hashmap is really unfortunate), and it's unlimited memory footprint is worrying. If we put a (configurable) upper limit on memory size, would that simplify the implementation @stbrody ?

**Comment by stbrody** [comment]
Thanks for the input @Hoverbear!

We could add a memory bound, but I'm a little worried about the performance cost of scanning every incoming Event to calculate its size to maintain the information of memory usage.

I also don't think doing so simplifies the design at all.  The problem is around providing both an efficient/understandable age-out policy while also providing fast lookup for determining if an Event is a duplicate.  I couldn't figure out a way to provide both with a single data structure, hence the hybrid vector/hashmap approach described.

I agree that a fixed `num_entries` approach is much simpler, safer, and more efficient.  It just comes down to user requirements in my mind.  The ticket description specifically mentioned windowing by a time range, so I felt it important to present an idea for how to achieve that.  It just depends on whether users would accept an approach based on number of entries rather than time range.  I'm not sure how best to ascertain that...  This is, however, why I put the config options nested under a `buffer` option, so that we could go with the `buffer.num_entries` approach for now and add a `buffer.seconds` option in the future if we determine it's necessary.

**Comment by binarylogic** [comment]
Thanks @stbrody 

> The ticket description specifically mentioned windowing by a time range

That was my fault and was probably too assuming. My intent is exactly what you described, a simple age-out policy. Starting with `num_items` makes sense to me for the first version. But this, in my opinion, is a worse user experience because it's hard to choose the right number. It's also prone to drift if the environment changes (volume changes, hardware changes, etc). I think we can provide reasonable guidance in the docs though.

**Comment by stbrody** [comment]
Okay great.  Definitely agreed that it's a less nice user experience due to being less obvious how to configure.  But probably worth it for the simplicity and safetly, at least for v1.

I'll go ahead and get started on the `num_items` approach and we can always revisit/add additional modes later.

Thanks!

**Comment by Hoverbear** [comment]
Awesome! Can't wait to review it!

**Comment by stbrody** [comment]
I'm proposing renaming `buffer.num_entries` to `cache.num_entries`.  I feel like "buffer" implies we queue up events before sending them out of the transform.  I think "cache" is a better description of what this transform is doing.

**Comment by binarylogic** [comment]
Agree 👍 , makes sense to me.

**Comment by lukesteensen** [comment]
Some interesting prior art on this problem: https://www.somethingsimilar.com/2012/05/21/the-opposite-of-a-bloom-filter/

**Comment by binarylogic** [comment]
Closed via https://github.com/timberio/vector/pull/1848
