### ISSUE TITLE
Add `sourcetype_field` option to `splunk_hec` sink

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#2142]
From https://github.com/timberio/vector/issues/2116#issuecomment-603413000: we need to add support for setting `sourcetype` in `splunk_hec` source.

Because different events might have many different `sourcetype` values, it makes sense to not specify it in the config, but read from one of the fields of the event. It can be accomplished by adding new `sourcetype_field` configuration option which would define which field of the event should be used as the `sourcetype` value.

**Comment by a-rodin** [comment]
I thought about it a bit more, and I think that actually it is better to add not a single field, but two related fields:

* `sourcetype_field.name` - optional string field which would specify name of the field which contains the sourcetype. If the field is not present it the event, `sourcetype` should not be inserted.
* `sourcetype_field.drop` - an optional boolean field, which would specify whether the field should be dropped from the original event or not. It can by `false` by default.

**Comment by binarylogic** [comment]
@a-rodin the field dropping reminds me of the new `encoding.exclude_fields` option. Couldn't we use that?

**Comment by a-rodin** [comment]
@binarylogic I think `encoding.exclude_fields` should work here, so I it makes sense to continue with the initial proposal about a single `sourcetype_field`.

**Comment by Alexx-G** [comment]
@a-rodin Thanks a lot for taking this one!
Would it make sense to address both `sourcetype` and `source` as part of this issue? It seems that the use case for both is quite similar.
I've checked some of our existing rules for splunk, we're setting both of them (otherwise they end up set to `source =	http:Target	| sourcetype =	httpevent` by splunk IIRC

**Comment by binarylogic** [comment]
@a-rodin just to make sure we're approaching this properly. It looks like Splunk has [a number of default fields](https://docs.splunk.com/Documentation/Splunk/7.0.0/Data/Aboutdefaultfields). Mapping these fields at the sink level is done throughout all of our sinks, and we should do this automatically for `splunk_hec` as well. For example, [notice how we map the `date` column in the `datadog_logs` sink](https://github.com/timberio/vector/blob/fe2e12ce89bc69657851a7a8f4dfeb3b4d334dc8/src/sinks/datadog/logs.rs#L90).

We should do the same thing here. I propose that we:

- [ ] Map our `log_schema().host_key()` to Splunk's `host` field.
- [ ] Map our `log_schema().timestamp_key()` to Splunk's `timestamp` field.
- [ ] Add a new `log_schema().source_key()` option. I like this concept in Splunk.
- [ ] Adjust the `file` source to use this field instead of `file_key`.
- [ ] Add a `source_key` option to the `http` source (this does _not_ replace the `host_key`).
- [ ] Add a `source_key` option to the `socket` source (this does _not_ replace the `host_key`).
- ... and the rest of the sources

If you agree, I can open issues for this. It should fairly simple to add throughout our sources.

**Comment by a-rodin** [comment]
@binarylogic

> - [ ] Map our `log_schema().host_key()` to Splunk's `host` field.
> - [ ] Map our `log_schema().timestamp_key()` to Splunk's `timestamp` field.

These two are already done.

> - [ ] Add a new `log_schema().source_key()` option. I like this concept in Splunk.
> - [ ] Adjust the `file` source to use this field instead of `file_key`.
> - [ ] Add a `source_key` option to the `http` source (this does _not_ replace the `host_key`).
> - [ ] Add a `source_key` option to the `socket` source (this does _not_ replace the `host_key`).

I think it makes sense, I would add to the list this:

- [ ] Adjust the `kafka` source to use `source_key` instead of [`key_field`](https://vector.dev/docs/reference/sources/kafka/#key_field).

However, I feel that the discussion of `source_key` should be separated from the discussion of `sourcetype`, as the latter is a small and Splunk-specific change, as opposed to adding a global `source_key` option.

**Comment by binarylogic** [comment]
Closing this in favor of https://github.com/timberio/vector/issues/2147. @Alexx-G let us know if this properly solves the problem.

**Comment by Alexx-G** [comment]
@binarylogic It indeed addresses the problem, thank you! It seems to be flexible enough so it would be possible to override them quite easy. Having these concept at log schema level makes a lot of sense.
