### ISSUE TITLE
Automatic timestamp extraction

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2255]
A _very_ common practice for logs is to prefix them with a timestamp, and having to set up a `*_parser` transform to extract this feels a little clunky given that this fits squarely in the observability domain. I'd like to propose the following:

- [ ] Vector should perform this extraction automatically during log creation. So, this would happen _within_ each relevant source.
- [ ] Ability to disable this on a per-source basis.
- [ ] We should use the exact same types defined [here](https://github.com/timberio/vector/blob/2cfe0090f40968305d18df5bf4727f0050f6848d/src/types.rs#L206-L229). In fact, this feature should be extracted so it can be shared.

Outstanding questions:

1. What do we do when the timestamp in the log lacks sufficient precision? For example, what if the log lacks seconds? Maybe the formats detected should, at least, require seconds.
2. How would this affect performance? If it is substantial we should discuss ways to improve this or allow the user to opt-in in such a way that would improve this. Ex: supplying an exact format.
3. Is this better off as an explicit transform? Is this too magical?
