### ISSUE TITLE
Remove `BatchEventsConifg` infavor of all sinks using `BatchBytesConfig`

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2411]
We should update our sinks to batch by bytes rather than some sinks batching by event.

- [ ] `aws_kinesis_streams`
- [ ] `aws_kinesis_firehose`
- [ ] `aws_cloudwatch_logs` (#2408)
- [ ] `aws_cloudwatch_metrics`
- [ ] `datadog_metrics`
- [ ] `influxdb_metrics`

**Comment by binarylogic** [comment]
@bruceg I'm assigning this to you since it's related to batch rework. I'm not sure this is still relevant.

**Comment by bruceg** [comment]
This will be closed by #2866
