### ISSUE TITLE
Smoke testing Vector pipelines

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3455]
Currently, Vector offers a few ways to test a newly built pipeline:

1. [`vector validate`](https://vector.dev/docs/administration/validating/) performs basic checks that your configuration is valid, but does not test actual data processing.
2. [`vector test`](https://vector.dev/docs/reference/tests/) runs any built-in unit tests that a user has added to their config.
3. And [`vector -config ...`](https://vector.dev/docs/administration/process-management/#starting) starts your pipeline, which can also be used to verify that your pipeline is working, but has the downside of actually writing data downstream.

But we still lack a basic smoke test feature that would be very useful during the development of pipelines.

## Requirements

The key differences/requirements for this feature are:

- [ ] Ability to test a single pipeline as it flows from a single source.
- [ ] Samples real-world data from hooked up sources with a configurable sample quantity.
- [ ] Does not send data from sinks unless explicitly told to.
- [ ] Prints helpful, detailed debug messages for failures that assist in pipeline building.

## Solution

1. We could expand `vector validate` to include smoke testing, but I'm unsure how we would target specific pipelines.
2. We could add a new subcommand `vector smoke-test`.
