### ISSUE TITLE
Remove tokio-compat

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#3478]
#3449 remove `tokio:0.1`, but we still have `tokio-compat` because use `futures:0.1` in a lot of places.

~Before remove `tokio-compat` I propose update all tests to `crate::test_util::test` macros (instead manually created `Runtime` in each test). Macros added in #3474.~

Plan:
- [x] Replace `runtime().block_on*` to `#[tokio::test]`. #3505 #3626 
- [x] Investigate why some test require `threaded_scheduler` and/or `core_threads = 2`. #3578 #3596 
- [x] Update benches #3626
- [x] Remove tokio-compat #3627

**Comment by MOZGIII** [comment]
Is the plan to also remove our `Runtime` abstraction along with the `tokio-compat`? The reason I'm asking is I think it may be useful even after tokio upgrade - however it's not totally *necessary* so we might want to cut it for simplicity...

**Comment by lukesteensen** [comment]
> Is the plan to also remove our `Runtime` abstraction along with the `tokio-compat`?

My assumption is that we will be using `Runtime` in extremely few places as we move off `tokio-compat` and onto `#[tokio::test]`. That makes it much less important and I'd be in favor of just removing it unless there is a good reason to keep it.
