### ISSUE TITLE
Improve data model ergonomics

### ISSUE THREAD

**Issue by vector-vic** [timberio/vector#3965]
## Summary
Our data model has grown organically over time in a way that only makes sense by accounting for the previous states. It is at a point where it is hindering performance and development of other features. Therefore, it's time that we reapproach it with everything we know.

## Jobs to be done
- As a contributor to Vector, the Event API should be easy to use and guide me towards a correct and performant implementation as much as possible
- As a developer working on event internals, I should be able to change representation specifics for performance, etc, without making sweeping changes to the whole Vector codebase

## Requirements
- [ ] Taking into account what we now know about performance, usage patterns, etc vs the history of Vector's data model, sketch out a desirable end-state API for events that would meet all the goals discussed above
- [ ] Given agreement on the desired end state, put together a plan of attack to get us to that state incrementally, without any big bang PRs that are likely to stall and negatively impact other development

## Out of scope
- [ ] Improving event performance

**Comment by vector-vic** [comment]
Link to feature: https://timber.productboard.com/feature-board/planning/features/5156479

**Comment by binarylogic** [comment]
Closing since the immediate work is done. We will follow up with a new epic if a need arises, like increasing performance.
