### ISSUE TITLE
Upgrade dependencies to tokio 1.0

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#5175]
`tokio:0.3` was [released](https://tokio.rs/blog/2020-10-tokio-0-3) a month ago. `dependabot` creates pull requests (like https://github.com/timberio/vector/pull/5158) with dependencies which were already updated, but we can not easily merge them. I did not research yet about any compatibility layer, maybe we will need to update everything at once or it will be possible to update crates independently, not sure. This is only a tracking issue with dependencies status regarding their update to new `tokio`.

`tokio:0.3` list (outdated because we will upgrade to `tokio:1.0` and skip `tokio:0.3`):

<details><summary>**Valid on `11/30/2020`:**</summary>

- [ ] [async-compression](https://github.com/Nemo157/async-compression) (tokio:0.3 — :heavy_check_mark: `>=0.3.6` https://github.com/Nemo157/async-compression/pull/104)
- [ ] [bollard](https://github.com/fussybeaver/bollard) (tokio:0.3 — :x: https://github.com/fussybeaver/bollard/issues/130)
- [ ] [goauth](https://github.com/akshayknarayan/hyper-unix-connector/issues/2) (tokio:0.3 — :x: https://github.com/durch/rust-goauth/issues/16)
- [ ] [h2](https://github.com/hyperium/h2) (tokio:0.3 — :heavy_check_mark:, git, `>=0.3.0` https://github.com/hyperium/h2/issues/499), not a direct dependency
- [ ] [hyper-openssl](https://github.com/sfackler/hyper-openssl) (tokio:1.0 — :heavy_check_mark: https://github.com/sfackler/hyper-openssl/issues/29)
- [ ] [hyper-rustls](https://github.com/ctz/hyper-rustls) (tokio:0.3 — :heavy_check_mark:, git, https://github.com/ctz/hyper-rustls/issues/123), not a direct dependency
- [ ] [hyper-tls](https://github.com/hyperium/hyper-tls) (tokio:0.3 — :x: https://github.com/hyperium/hyper-tls/issues/76), not a direct dependency
- [ ] [hyper-unix-connector](https://github.com/akshayknarayan/hyper-unix-connector) (tokio:1.0 - :heavy_check_mark:, https://github.com/akshayknarayan/hyper-unix-connector/issues/2), not a direct dependency
- [ ] [hyper](https://github.com/hyperium/hyper) (tokio:0.3 — :heavy_check_mark:, git, `>=0.14.0` https://github.com/hyperium/hyper/issues/2302 milestone: https://github.com/hyperium/hyper/milestone/6)
- [ ] `lib/file-source` (tokio:0.3 — :x:)
- [ ] `lib/vector-api-client` (tokio:0.3 — :x:)
- [ ] [mongodb](https://github.com/mongodb/mongo-rust-driver) (tokio:0.3 — :x: https://github.com/mongodb/mongo-rust-driver/pull/267)
- [ ] [pulsar](https://github.com/wyyerd/pulsar-rs) (tokio:0.3 — :x: https://github.com/wyyerd/pulsar-rs/issues/121)
- [ ] [rdkafka](https://github.com/fede1024/rust-rdkafka) (tokio:0.3 — :heavy_check_mark:, git, `>0.25.0` https://github.com/fede1024/rust-rdkafka/issues/298)
- [ ] [reqwest](https://github.com/seanmonstar/reqwest) (tokio:0.3 — :x: https://github.com/seanmonstar/reqwest/issues/1060)
- [ ] [rusoto_*](https://github.com/rusoto/rusoto) (tokio:0.3 — :x: https://github.com/rusoto/rusoto/issues/1845)
- [ ] [stream-cancel](https://github.com/jonhoo/stream-cancel) (tokio:0.3 — :heavy_check_mark: https://github.com/jonhoo/stream-cancel/pull/8)
- [ ] [tokio-native-tls](https://github.com/tokio-rs/tls) (tokio:0.3 — :heavy_check_mark: https://github.com/tokio-rs/tls/pull/31), not a direct dependency
- [ ] [tokio-openssl](https://github.com/sfackler/tokio-openssl) (tokio:0.3 — :heavy_check_mark: https://github.com/sfackler/tokio-openssl/pull/21), not a direct dependency
- [ ] [tokio-test](https://github.com/tokio-rs/tokio) (tokio:0.3 — :heavy_check_mark: https://github.com/tokio-rs/tokio/pull/2747)
- [ ] [tokio-tls](https://github.com/tokio-rs/tokio-tls) (tokio:0.3 — :x:), not a direct dependency
- [ ] [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite) (tokio:0.3 — :heavy_check_mark: https://github.com/snapview/tokio-tungstenite/pull/125), not a direct dependency
- [ ] [tokio-util](https://github.com/tokio-rs/tokio) (tokio:0.3 — :heavy_check_mark: https://github.com/tokio-rs/tokio/pull/2747)
- [ ] [tower-test](https://github.com/tower-rs/tower) (tokio:0.3 — :heavy_check_mark:, git, https://github.com/tower-rs/tower/pull/476)
- [ ] [tower](https://github.com/tower-rs/tower) (tokio:0.3 — :heavy_check_mark:, git, https://github.com/tower-rs/tower/pull/476)
- [ ] [trust-dns-proto](https://github.com/bluejekyll/trust-dns/tree/main/crates/proto) (tokio:0.3 — :heavy_check_mark:, alpha released, https://github.com/bluejekyll/trust-dns/pull/1262), not a direct dependency
- [ ] [trust-dns-resolver]() (tokio:0.3 — :heavy_check_mark:, alpha released, https://github.com/bluejekyll/trust-dns/pull/1262), not a direct dependency
- [ ] [warp](https://github.com/seanmonstar/warp) (tokio:0.3 — :x: https://github.com/seanmonstar/warp/issues/725)
</details>

Will create new list (with `tokio:1.0`) when we close https://github.com/timberio/vector/issues/5103.

**Comment by binarylogic** [comment]
@kirillt it might be worth opening issues on each repo first if they don't already exist. Would you mind doing that?

**Comment by kirillt** [comment]
@fanatid :)

**Comment by fanatid** [comment]
@binarylogic I updated the issue (tracking issues added). Before we start work on `tokio` upgrade I think we need to finish with `futures`: https://github.com/timberio/vector/issues/5103.

**Comment by binarylogic** [comment]
Thanks @fanatid, sounds good.

**Comment by juchiast** [comment]
tokio 1.0 is out!

**Comment by fanatid** [comment]
Yep, maybe we will skip 0.3 and switch directly to 1.0. I'm not sure that all listed crates above will support 0.3...
https://tokio.rs/blog/2020-12-tokio-1-0

**Comment by juchiast** [comment]
Yeah, hyper already released 1.0-compatible version, and I think warp will be updated soon.

**Comment by jamtur01** [comment]
Look like go-auth has released 0.9.0 which upgrades to tokio 1.0

**Comment by fanatid** [comment]
@lukesteensen started work on this in https://github.com/timberio/vector/pull/5872
