### ISSUE TITLE
K8s roadmap and projects summary

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5847]
We need a simple Kubernetes document that outlines all of the high-level projects and their associated details. This is a starting point for firming up our k8s roadmap.

- [ ] Create sections for each Kubernetes project.
- [ ] Describe what the project does.
- [ ] Describe the value of the project.
- [ ] Describe caveats and drawbacks.
- [ ] Associate every single [kubernetes issue](https://github.com/timberio/vector/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22platform%3A+kubernetes%22) with a project.
- [ ] Provide a recommendation for closing, deferring, or proceeding with the project.
- [ ] If we should do the project, outline a simple plan of attack.

The projects that I'm aware of are:

- [ ] K8s non-file log source support (which includes support for journald, the k8s transform, etc)
- [ ] K8s metrics support (collection and tight integration with Prometheus)
- [ ] K8s cluster-level operator deployment (#5362)
- [ ] K8s support for Vector YAML configuration
- [ ] K8s advanced exclusion/filtering options
- [ ] K8s bugs that we are currently aware of
- [ ] K8s aggregator role
- [ ] K8s cluster events
- [ ] K8s tech debt
- [ ] K8s hosted platforms (EKS, GKS, etc)
- [ ] K8s operator/enterprise/pie-in-the-sky offering

**Comment by MOZGIII** [comment]
👍 
Note that individual projects will likely have very large overlaps with each other in terms of the implementation, hence why I went with organizing them into the bigger steps at the roadmap plan.
It would be nice to have to elide the individual projects though, to pick what do we and what do we not want to implement.

It is also a bit hard to figure out the individual projects in the later steps of the said roadmap without going into a long design phase waterfall-style (which I assume would not be the best fit for us). I suggest that we integrate with this process of identifying the projects at each of the roadmap steps, rather than doing it one time upfront.
