### ISSUE TITLE
Final config validation meta issue

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#603]
We've had a lot of disparate changes happen over time with our config parsing
and validation. So I thought it worthy to create a higher-level issue that covers
all of the ways we want to validate Vector's configuration. It's likely all of these
are already done, but I would like to confirm and have someone re-approach
this with the complete context.

### Description

To ensure Vector is user friendly we need to catch config validation errors
early. This not only saves the user time when debugging, but it allows
operators to strictly validate configuration before deploying changes. This
helps prevent bad configuration from being deployed.

### Requirements

Most of this is probably handled when parsing the TOML, and if that's the case
you can check them off, but I wanted to include everything to make sure we're
covering it all:

**Validation should fail if...**

- [x] An unknown key is present for both the root level and all of the
      component definitions. (probably handled by parsing)
- [x] Any of the `inputs` values reference unknown components (bad references).
- [x] The `inputs` value is blank or empty (at least one value must be supplied).
- [x] No sources are defined
- [x] No sinks are defined
- [x] If any of the above errors are present Vector will exit immediately with
      an exit code of `1` (this represents config errors)
- [x] A `--dry-run` flag can be used to perform validation _only_. If
      config valdiation fails the process will exit with a `1`, if it succeeds
      the process will exit with a `0`.
- [x] If the `--require-healthy` flag is passed along with the `--dry-run`
      flag then healthchecks will be included in the overall validation process.
      Meaning, if a healthcheck fails the process will exit with a `1` and if
      they all succeed the process will exit with a `0`.
- [ ] This validation should be performed upon reloading (`SIGHUP`), log an
      error, and reject the new configuration (preserving previous config). I
      believe this is already the case but I want to confirm.

**Comment by binarylogic** [comment]
@kirillt does this issue make sense? I just wanted to see if you could check this off before moving on since you have context on all of this.

**Comment by kirillt** [comment]
> If any of the above errors are present Vector will exit immediately with
an exit code of 1 (this represents config errors)
We discussed earlier to add exit code 78 in this case (I also changed some other cases).
78 means "something was found in an unconfigured or misconfigured state"
I can change this to 1 for simplicity. Would it be better?

**Comment by kirillt** [comment]
Things to fix:

1. > An unknown key is present for both the root level and all of the
component definitions. (probably handled by parsing)

    Works for components, but not for root level.

**Comment by binarylogic** [comment]
> We discussed earlier to add exit code 78 in this case

👍 that's perfect, no need to change.

Regarding your other issues. Would you like me to create follow issues or is this issue enough to address those?

**Comment by kirillt** [comment]
@binarylogic
Points `1` and `2` are OK in scope of this issue for sure. Probably `3` is more relevant to some other scope, but for me it's OK to do it here as well after `1` and `2`.

**Comment by kirillt** [comment]
`1`, `2` and `3` fixed in PR. It seems that failed reload of a config could leave topology in semi-loaded state. I will check it in next couple of days.

**Comment by binarylogic** [comment]
Thanks! Yes, if that is indeed an issue, could you open a separate issue to represent your findings?

**Comment by kirillt** [comment]
I was wrong, reload doesn't leave topology in semi-load state.
But if we can't parse config then it exits. I have fixed this in new small PR.

**Comment by binarylogic** [comment]
Great, thanks! This looks good.
