### ISSUE TITLE
Require the `data_dir` option for the `file` source and default it to the global `data_dir`

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#644]
Currently, the `file` source requires a `data_dir` for checkpointing, yet this requirement is not enforced when Vector is started. You can see [here](https://github.com/timberio/vector/blob/b420159287f19a2aa4405da6f90fcea733d9de28/src/sources/file.rs#L44) that the `data_dir` option defaults to an empty path. This should not be allowed since an explicit data directory should be specified to store the checkpoint positions.

### Requirements

- [ ] Default the `file` source `data_dir` option to the global `data_dir`
- [ ] Exit on start if the `file` source `data_dir` option is empty.
- [ ] Allow the user to pass a `data_dir` option in the file source itself to override the global `data_dir`.

**Comment by seeekr** [comment]
#673 should solve this and tick all 3 boxes.
