### ISSUE TITLE
Preconfigured dashboards

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6519]
## Summary
Vector's internal metrics system is flexible but has no opinion on where its data should be sent or how it should be displayed. To provide a good onboarding experiment for new users, we should have a simple blessed path that gets them high-quality dashboards out of the box, without sacrificing that flexibility for more advanced users.

## Jobs to be done
- As a new Vector user, I need a turnkey solution to monitor Vector itself to ensure that it is performing as I expect
- As a Datadog and Vector user, I expect the two tools to have a seamless, high-quality integration that automatically gathers and presents all the information I need to understand behavior

## Requirements
- [ ] Add a new global option via which to configure sending internal metrics directly to Datadog
- [ ] Build a set of preconfigured dashboard in Datadog that are populated automatically when receiving internal metrics from Vector
- [ ] Ensure that all key performance indicators of Vector are collect, sent, and presented via this system

## Out of scope
- To start, this can focus on generic Vector metrics as opposed to dynamically configuring dashboards specific to each configuration

**Comment by jszwedko** [comment]
This is stale and has been replaced by other epics regarding internal insrumentation.
