### ISSUE TITLE
Next steps for `aws_cloudwatch_logs` sink

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#683]
Cloudwatch is close to being fully featured. There are a few final last stages.

## Requirements

- [ ] Support template interpolation for log groups (#476)
- [ ] Dynamically create log groups (#476)
- [ ] Support less invasive permissions for healthchecks (#624)

### Less invasive healthchecks

For this, there are three possible healthchecks we can perform based on the provided config options.

1. The user-provided a `stream_name` and a `group_name` that are static. In this case, we attempt to create the log stream, and if it exists we pass otherwise we try to create it. This means that the healthcheck will always pass if we are able to contact AWS and if the permissions are setup correctly.

2. The user provided a `group_name` but provided a dynamic `stream_name`. In this case, we do not know the stream at healthcheck time so we must attempt to create a test stream. There should be a default `vector-test` stream that is created to attempt to see if we can actually create log streams and then put to them.

3. The user provided a dynamic `group_name` and `stream_name` in this case just as above, the user must provide a test `group_name` to healthcheck against and then we use the default `vector-test` stream name. The user can also override the test stream name.

@bittrance since you had some thoughts around this, I'd love to hear if this sounds good to you. :)

cc @binarylogic @lukesteensen 

Related to #624 and #476

**Comment by lukesteensen** [comment]
Overall this sounds reasonable to me.

The tradeoff between comprehensive healthchecks, dynamic targets, minimal permissions, and amount of configuration options is a real bummer. I don't think we should go too far with adding configs and workarounds for these types of things (at least until users ask for them), but it'd be good to get something like #621 in place so that no one gets stuck in the meantime.

**Comment by LucioFranco** [comment]
Another thing is if dynamic groups are supplied for now we can punt on more complex healthchecks and just print a warning that the healthcheck wasn't run and have it just return right away as a success.

**Comment by binarylogic** [comment]
Noting, for now we're going to disable healthchecks if a dynamic value is found in the `group_name`. We can reapproach this when we decide how we want to handle healthchecks for these kinds of things.

**Comment by binarylogic** [comment]
@LucioFranco any reason this was not closed?

**Comment by BorjaSalazar** [comment]
Hi, sorry to open this again, but i'm unable to configure vector aws_cloudwatch_logs sink. It seems it is not detecting correctly the group_name as a template value and thus not skipping the healthcheck. I'm using vector 0.20.0.

**Comment by jszwedko** [comment]
Hi @BorjaSalazar !

I think that issue is being tracked as https://github.com/vectordotdev/vector/issues/10787
