### ISSUE TITLE
Tools for understanding performance in user environments

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#6935]
## Summary
Our biggest challenge in supporting large users has been in understanding why Vector is performing at a given throughput in the customer environment. We have relied heavily on intuition and experimentation due to a lack of detailed data from Vector itself, which does not lead to good outcomes.

## Jobs to be done
- When a customer comes to us with a performance related question, we should have a simple process via which they can collect a standard set of data to give to us for analysis
- This data should be sufficiently detailed to identify bottlenecks and generate suggestions without requiring a laborious back-and-forth between the Vector team and the customer

## Requirements
- [ ] Collect performance debugging data, including per-component throughput and utilization, concurrency information, and measurements of significant operations within each component
- [ ] Mechanism to quickly and easily expose performance debugging data to users
- [ ] Documentation on collecting standard performance debugging data

## Out of scope
- Data does not need to be automatically submitted anywhere, just output in some form
- Display of the data is not required, as it is intended mostly to be passed from the user to the Vector team for analysis

**Comment by blt** [comment]
This strikes me as a duplicate of #7638 in that we intend for the instrumentation we're building as a part of soak testing to serve in diagnosing user issues. I'm inclined to close this out unless we have a different notion for user debug work.

**Comment by lukesteensen** [comment]
Closing as a duplicate of both the soak tests and the tracing work represented in #8025.
