### ISSUE TITLE
Vector agent HTTP ingestion

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#7137]
## Summary

This epic contains all of the work necessary to easily ingest _log_ data from upstream Vector agents.

## Jobs to be done

1. When a Vector aggregator is deployed on-prem, a user should be able to easily configure upstream Vector agents to send data to it.
2. When data is received in Vector from upstream Vector agents, it should preserve agent-level metadata and structure.

### Data

- [ ] All Vector data types: log and metrics.

### Vector Agent

- [ ] Ability to provide one or more addresses within the Vector configuration that point to the downstream Vector aggeregator.
  - [ ] DNS should be supported for service discovery, this come OOTB with DNS on k8s
  - [ ] Multiple addresses allow for load balancing and failover

### Vector Aggregator

TBD

## Out of scope

- Loading of Datadog pipelines and processing of the data is covered in a separate epic.

**Comment by amitde69** [comment]
@JeanMertz any reason why this was closed ?

**Comment by jszwedko** [comment]
@amitde69 this is supported for logs now. Metrics support will be added as part of #3994
