### ISSUE TITLE
Disk buffer bugs tracking issue

### ISSUE THREAD

**Issue by ktff** [timberio/vector#7425]
Tracking issue for various bug issues related to disk buffer, their causes, and fixes.

Issues (work in progress):
* Many ldb files (probably low I/O ops) (#document) (separate uncompact compaction could help) (fragmentation? it would be a self perpetuating loop) (#7264 aggravates it) (fix #7614)
   * #6602
   * https://github.com/timberio/vector/issues/7246#issuecomment-832289625

* High idle cpu utilization (#6597 could help) (fix #7615)
   * https://github.com/timberio/vector/issues/7246#issue-867605548
   * https://github.com/timberio/vector/issues/7246#issuecomment-831563998
   * https://github.com/timberio/vector/issues/7246#issuecomment-833885019

* Retaining ldb files, unbounded memory use (fix #6597) (fix #7614)
   * https://github.com/timberio/vector/issues/7246#issuecomment-832218081

* Large initial load (~~fix #7408~~ unacceptable increase of startup time)(fix #7522) 
   * https://github.com/timberio/vector/issues/6741#issuecomment-799557456
   * https://github.com/timberio/vector/issues/7246#issuecomment-833885019

* Blocked sink (#6597 could help) (fixes made during move to future 0.3 have maybe fixed it) (slow disk) (partial fix #7615)
    * #6741

### Todo
- [x] #6597
- [x]  #7522
- [x] ~~#7408~~ wasn't acceptable
- [x] Batch deletes  #7615
- [x] Min uncompacted size #7614
- [x] Document disk buffer memory behavior. #7679
      * It will use memory proportional to disk size.
      * ~~It can be slightly larger on disk than the configured `max_size`.~~
      * ~~Clarify use case.~~
      * Mention low disk performance related issues.
- [x] Notify relevant users when fixes get released to recheck them.

**Comment by ktff** [comment]
### Residual ldb files 

Bug where a large number of ldb files are never removed and just keep accumulating has been further aggravated by https://github.com/timberio/vector/pull/7264 PR. With that PR the following config reproduces the issue
```
data_dir = "./../tmp"

[sources.source0]
  type = "generator"
  format = "shuffle" 
  lines = ["line"] 
  sequence = true
  interval = 0.1

[sinks.sink1]
  type = "blackhole"
  inputs = ["source0"] 
  buffer.max_size = 10000000000
  buffer.type = "disk" 
  buffer.when_full = "block" 
```

The main factor is the interval, that is if total emitted bytes in 1min is less than 1MB there is a chance that compaction will leave behind a ldb file. The less bytes emitted, greater the chance. The above config leaves every file while emitting 400KB in 1min

On our side, we can fix it by limiting compaction to happen only if we have 2MB or more of uncompacted bytes. We could go for a lower bound but, just to be safe, 2MB is the max size of ldb files and there is a chance that the bug happens for sizes greater than 1MB but it requires ever so more time to materialize.

**Comment by ktff** [comment]
> I think the max size of the ldb files is actually 4 MB

Hmm, then it's more dynamic than I thought. So let's go with 4MB.

**Comment by ktff** [comment]
Fixes for every issue have been merged and relevant users notified so I'll be closing this. Subsequent follow ups on the bugs/fixes can be done in individual issues.
