### ISSUE TITLE
First-class support for running Vector-as-an-aggregator in AWS EKS

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8218]
## Summary
We would like to have a high level of confidence that our users are able to deploy Vector-as-an-aggregator  on to AWS EKS, now and in the future.

## Requirements
- [ ] Automated test for aggregator on AWS EKS
- [ ] Documentation for deploying on AWS EKS

## Out of scope
- [x] Using AWS load balancers instead of HA Proxy. We've decided to punt on that for now and revisit later as a project across all the cloud providers we support.
- [x] Collecting Kubernetes component logs for EKS ([ref](https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html))

**Comment by spencergilbert** [comment]
Testing with Terraform and eksctl, it would take ~10-15minutes to create a clean EKS cluster. That seems like too long for a "run on every PR" CI job, but less of an issue if we just run it for releases/tags or nightly.

@jszwedko what are your thoughts?

**Comment by jszwedko** [comment]
Nice, thanks for looking into that. I agree that that seems like a bit much to do on every PR. My thoughts are we either:

* Do the clean cluster approach, but just run nightly. Optionally allow tagging PRs like we do for the current k8s tests to run them.
* Just have one long-lived cluster that we run the tests on, but ensure the tests are appropriately isolated. If we did this, we could probably run them on each PR or on master commits.

I think either one is workable. I have a slight preference for just having a long running cluster.

Notably we might want to think about how to enable us to run these tests on-demand during development too in-case we have to debug one or while adding to the test suite.

**Comment by spencergilbert** [comment]
> Nice, thanks for looking into that. I agree that that seems like a bit much to do on every PR. My thoughts are we either:
> 
> * Do the clean cluster approach, but just run nightly. Optionally allow tagging PRs like we do for the current k8s tests to run them.
> * Just have one long-lived cluster that we run the tests on, but ensure the tests are appropriately isolated. If we did this, we could probably run them on each PR or on master commits.
> 
> I think either one is workable. I have a slight preference for just having a long running cluster.
> 
> Notably we might want to think about how to enable us to run these tests on-demand during development too in-case we have to debug one or while adding to the test suite.

There is no clean way to truly isolate workloads on the same cluster, there will be some contamination due to co-location on the nodes.

For the local usage, it should be trivial - we can already run the e2e tests at an arbitrary cluster. You'd just need to get an appropriate kubeconfig for the remote cluster

**Comment by spencergilbert** [comment]
Had a quick call to discuss testing strategy with @jszwedko 

In terms of determining that Vector, running as an aggregator, is valid for a particular Kubernetes provider has more to do with the Helm chart configuration rather than any functionality or implementation of Vector itself. Running Vector as an aggregator on a Debian VM should be no different than running it in Kubernetes with the Debian based image (functionally). Our integration tests for sinks and source should be suitable to catch any regressions.

I propose we use [chart-testing](https://github.com/helm/chart-testing) to install the aggregator chart in with a set of predefined configurations (vector agent/datadog agent/fluent/etc to elasticsearch/s3/loki/datadog/etc) to ensure our resources are valid given the platform and the pod successfully boots (it should fail healthchecks if missing required configurations).

This lowers the effort of implementing and testing, as well as reducing the time required to run the CI job.

@binarylogic @StephenWakely @JeanMertz - do you have any objections to this?

**Comment by binarylogic** [comment]
Sounds reasonable to me, but would like to hear from others that have more k8s experience.

**Comment by jszwedko** [comment]
Replaced by

https://github.com/timberio/vector/issues/8477
https://github.com/timberio/vector/issues/8478
