### ISSUE TITLE
First-class support for running Vector-as-an-aggregator in Azure AKS

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8294]
## Summary
We would like to have a high level of confidence that our users are able to deploy Vector-as-an-aggregator  on to Azure AKS, now and in the future.

## Requirements
- [ ] Automated test for aggregator on Azure AKS
- [ ] Documentation for deploying on Azure AKS

## Out of scope
- [ ] Using Azure load balancers instead of HA Proxy. We've decided to punt on that for now and revisit later as a project across all the cloud providers we support.
- [ ] Collecting Kubernetes component logs for AKS

**Comment by jszwedko** [comment]
Replaced by

https://github.com/timberio/vector/issues/8477
https://github.com/timberio/vector/issues/8478
