### ISSUE TITLE
Release Vector-as-aggregator

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#8478]
Copying notes:

* Add aggregator in installation docs
* Add EKS/GKS/AKS page (can just link to the kubectl / helm pages)
* Add cloud-specific how it works sections (ex: AWS permissions)
* Add release highlight
* Confirm that we can send a link to a customer and get setup properly
* Add new k8s aggregator soak test into core teams soak test framework (sync with Toby since he is adding an agent k8s test)

**Comment by spencergilbert** [comment]
We'll also need to update the management docs here: https://vector.dev/docs/administration/management/#helm

**Comment by spencergilbert** [comment]
## Jobs to be done

- [ ] Add aggregator to [helm installation docs](https://vector.dev/docs/setup/installation/package-managers/helm/) (https://github.com/timberio/vector/issues/5041)
- [ ] Add release highlight (https://github.com/timberio/vector/issues/8742)
- [ ] Tag this as a public beta (should be included in one/both of the above issues)
- [ ] Add new k8s aggregator soak test into core teams soak test framework
- [ ] Pull logs and metrics from haproxy
  - [ ] Configurable vector sidecar for haproxy to pull metrics/logs (https://github.com/timberio/vector/issues/7578)
  - [ ] Documentation for using datadog-agent (https://github.com/timberio/vector/issues/8743)
- [ ] Ensure https://docs.datadoghq.com/agent/vector_aggregation/#overview is up-to-date
